#!/usr/bin/env bash
# Using your _debugging skills, find out what’s keeping your Ubuntu
# container’s _Nginx installation from listening on port 80. Feel free
# to _install whatever tool you need, _start and destroy as many _containers
# as you need to debug the issue. Then, _write a Bash script with the
# minimum number of _commands to automate your fix.
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start
